package com.example.aigame.util

import com.example.aigame.R
import com.example.aigame.domain.CollectionCardModel
import com.example.aigame.domain.RoomCardModel
import com.example.aigame.domain.ShopCardModel

object Constant {
    val furniture = listOf<ShopCardModel>(
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_1,
            R.string.shop_furniture_card_1_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_2,
            R.string.shop_furniture_card_2_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_3,
            R.string.shop_furniture_card_3_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_4,
            R.string.shop_furniture_card_4_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_5,
            R.string.shop_furniture_card_5_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_6,
            R.string.shop_furniture_card_6_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_7,
            R.string.shop_furniture_card_7_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_8,
            R.string.shop_furniture_card_8_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_9,
            R.string.shop_furniture_card_9_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_10,
            R.string.shop_furniture_card_10_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_11,
            R.string.shop_furniture_card_11_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_12,
            R.string.shop_furniture_card_12_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_13,
            R.string.shop_furniture_card_13_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_14,
            R.string.shop_furniture_card_14_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_15,
            R.string.shop_furniture_card_15_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_furniture_image_16,
            R.string.shop_furniture_card_16_name,
        ),
    )

    val chinese_art_and_decor = listOf<ShopCardModel>(
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_1,
            R.string.shop_chinese_art_and_decor_card_1_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_2,
            R.string.shop_chinese_art_and_decor_card_2_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_3,
            R.string.shop_chinese_art_and_decor_card_3_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_4,
            R.string.shop_chinese_art_and_decor_card_4_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_5,
            R.string.shop_chinese_art_and_decor_card_5_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_6,
            R.string.shop_chinese_art_and_decor_card_6_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_art_and_decor_image_7,
            R.string.shop_chinese_art_and_decor_card_7_name,
        ),
    )

    val chinese_zodiac = listOf<ShopCardModel>(
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_1,
            R.string.shop_chinese_zodiac_card_1_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_2,
            R.string.shop_chinese_zodiac_card_2_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_3,
            R.string.shop_chinese_zodiac_card_3_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_4,
            R.string.shop_chinese_zodiac_card_4_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_5,
            R.string.shop_chinese_zodiac_card_5_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_6,
            R.string.shop_chinese_zodiac_card_6_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_7,
            R.string.shop_chinese_zodiac_card_7_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_8,
            R.string.shop_chinese_zodiac_card_8_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_9,
            R.string.shop_chinese_zodiac_card_9_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_10,
            R.string.shop_chinese_zodiac_card_10_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_11,
            R.string.shop_chinese_zodiac_card_11_name,
        ),
        ShopCardModel(
            100000,
            R.drawable.icon_chinese_zodiac_image_12,
            R.string.shop_chinese_zodiac_card_12_name,
        ),
    )
    val smallRoomList = mutableListOf<RoomCardModel>()
    val listBuying = mutableListOf<CollectionCardModel>()
}